CREATE DATABASE WAAP;

GRANT ALL ON WAAP.* TO 'branch' IDENTIFIED BY 'web2014'

USE WAAP;

--회원 DB--
CREATE TABLE USER (
	USER_ID VARCHAR(20) PRIMARY KEY,
	USER_PWD VARCHAR(20) NOT NULL,
	USER_BIRTH DATE NOT NULL
);

--신청역 DB--
CREATE TABLE JOIN (
	USER_ID VARCHAR(20) FOREIGN KEY REFERENCES USER(USER_ID),
	PLACE VARCHAR(20) NOT NULL,
	TIME INT NOT NULL
);

--채팅 리스트 DB--
CREATE TABLE CHATLIST(
);
