CREATE DATABASE WAAP;

USE WAAP;

CREATE TABLE User (
	USER_ID VARCHAR(20) UNIQUE PRIMARY KEY,
	USER_PWD VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	USER_BIRTH DATE NOT NULL,
	USER_GEN VARCHAR(20),
	USER_AGE VARCHAR(20),
	INTRODUCE TEXT
);

CREATE TABLE JoinUser(
	No INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID VARCHAR(20),
	StationNo INT,
	JoinTime INT
);

INSERT INTO User(USER_ID, USER_PWD, USER_NAME, USER_BIRTH)
VALUES ('kim', 'asdf', 'sangwoo', '1989-11-13');

INSERT INTO User(USER_ID, USER_PWD, USER_NAME, USER_BIRTH)
VALUES ('park', 'asdf', 'juhong', '1985-08-09');

CREATE TABLE Station (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	station VARCHAR(80) NOT NULL,
	numOfMember INT,
	12Member INT,
	13Member INT,
	14Member INT,
	15Member INT,
	16Member INT,
	17Member INT,
	18Member INT,
	19Member INT,
	20Member INT,
	21Member INT,
	22Member INT,
	23Member INT,
	24Member INT
);

CREATE TABLE Chats (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(80) NOT NULL,
	message VARCHAR(250) NOT NULL
);