CREATE DATABASE wp_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

GRANT ALL ON wp_test.* TO 'id001'@'localhost' IDENTIFIED BY 'pwd001';
GRANT ALL ON wp_test.* TO 'id001'@'%' IDENTIFIED BY 'pwd001';

use wp_test;


CREATE TABLE temp_board (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	name VARCHAR(100) NOT NULL,
	pwd VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL, 
	content TEXT NOT NULL,
	postdate DATETIME NOT NULL,
	hits int(4) unsigned NOT NULL DEFAULT '0',
	likehits int(4) unsigned NOT NULL DEFAULT '0'
);

CREATE TABLE temp_user (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	name VARCHAR(100) NOT NULL,
	userid VARCHAR(100) NOT NULL,
	pwd VARCHAR(255) NOT NULL,
	level INT NOT NULL DEFAULT '0'
);

