CREATE DATABASE WAAP;

GRANT ALL ON WAAP.* TO 'branch' IDENTIFIED BY 'web2014'
GRANT ALL ON WAAP.* TO 'branch'@'%' IDENTIFIED BY 'web2014'

USE WAAP;

CREATE TABLE USER (
	USER_NAME VARCHAR(20) NOT NULL,
	USER_ID VARCHAR(20) PRIMARY KEY,
	USER_PWD VARCHAR(20) NOT NULL,
	USER_BIRTH DATE NOT NULL
);

CREATE TABLE JOIN (
	USER_ID VARCHAR(20) FOREIGN KEY REFERENCES USER(USER_ID),
	PLACE VARCHAR(20) NOT NULL,
	TIME INT NOT NULL
);

CREATE TABLE CHATLIST(
);
